### ISSUE TITLE
Defender Torpedo function not doing damage to both grids

### ISSUE THREAD

**Issue by Blaylock1988** [dorimanx/DePatch#5]
I hope you don't mind others adding issues here. I'm an admin on the Guardians Vanilla server and use DePatch but there is a critical bug with the Defender function:

The Defender > Protect Grids > Torpedo exclusion for ramming is ONLY damaging the torpedo grid, and is not damaging the target/hit grid. This function is not useful in any way until this is fixed.

Currently:
> Torpedo hits target, Torpedo takes damage, BUT Target does not take damage

Expected:
> Torpedo hits target, BOTH Torpedo AND Target takes damage

**Comment by dorimanx** [comment]
I have removed this part of code as it's was never working as expected.
Game logic is weird about this and making it work, will be too much work and debug.

For now this is marked as "game limit"
