### ISSUE TITLE
Bug with gun characters

### ISSUE THREAD

**Issue by AlphonseBruet** [dorimanx/DePatch#6]
Hello,

I have a problem, the damage of handle weapons such as automatic rifle etc from the server was disabled  on all the map,

We have an fps combat zone outside of the pve zone and the weapons put us at 0 hp but do not kill us and when we open our helmet suffocate and see if death is activated life goes back to 100% before descend normally by suffocation. which clearly defines manual weapons as inactive in damage.

Turrets work correctly outside of the PVE area.

 here is a test video without the "depatch" plug-in on the server and 9000 km from the PVE zone
https://www.youtube.com/watch?v=EZS6B_lbyxs

And here is the video with the DEPatch plug-in always installed 9000 km from the pve zone, we can note that the ammunition of the rifle does not go down, the life of my guinea pig has gone down to 0 but it is not dead and its life is climbed back to 100% when he opened his helmet to suffocate before descending normally.
https://www.youtube.com/watch?v=y6XwJc7hmts

I try with the version 1.8.38 and same problem.

**Comment by dorimanx** [comment]
When server start, there is 4minutes no damage protection to allow all grids to load to ram.
no matter where you are.

Also please make sure that pve zone coordinates are correct! and zone range is set in meters.

I have tested this issue, and me and my friend can shoot each other outside the zone as expected.
when we go to zone sphere we cant and i see what you have shown, as this is as expected inside the pve zone.

Please try the latest build.

**Comment by AlphonseBruet** [comment]
Hello Dorimanx,

I tested with the latest version and the new weapons, the problem remains the same.

Ammo count does not go down

there is also no damage to players / ships with hand weapons while ship weapons are working.

I am attaching the configuration file of our server to you.
[DePatch.txt](https://github.com/dorimanx/DePatch/files/6370196/DePatch.txt)
